export const SHOW_ALERT="SHOW_ALERT";
export const CLEAR_ALERT= "CLEAR_ALERT";
export const REGISTER_USER_BEGIN="REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR";
export const LOGIN_USER_BEGIN="REGISTER_USER_BEGIN";
export const LOGIN_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const LOGIN_USER_ERROR="REGISTER_USER_ERROR";
export const LOGOUT_USER="LOGOUT_USER";

export const INCOME_FETCH_BEGIN="INCOME_FETCH_BEGIN";
export const INCOME_FETCH_SUCCESS="INCOME_FETCH_SUCCESS";
export const INCOME_FETCH_ERROR="INCOME_FETCH_ERROR";

export const EXPENSE_FETCH_BEGIN="EXPENSE_FETCH_BEGIN";
export const EXPENSE_FETCH_SUCCESS="EXPENSE_FETCH_SUCCESS";
export const EXPENSE_FETCH_ERROR="EXPENSE_FETCH_ERROR";


export const DELETE_INCOME_BEGINS="DELETE_INCOME_BEGINS";
export const DELETE_EXPENSE_BEGINS="DELETE_EXPENSE_BEGINS";

export const TRANSACTION_ADD_BEGINS="TRANSACTION_ADD_BEGINS";
export const TRANSACTION_ADD_SUCCESS="TRANSACTION_ADD_SUCCESS";
export const TRANSACTION_ADD_ERROR="TRANSACTION_ADD_ERROR";


export const SET_INCOME_EDIT="SET_INCOME_EDIT";
export const SET_EXPENSE_EDIT="SET_EXPENSE_EDIT";


export const EDIT_TRANSACTION_BEGINS="EDIT_TRANSACTION_BEGINS";
export const EDIT_TRANSACTION_SUCCESS="EDIT_TRANSACTION_SUCCESS";
export const EDIT_TRANSACTION_ERROR="EDIT_TRANSACTION_ERROR";


export const STATS_FETCH_BEGINS="STATS_FETCH_BEGINS";
export const STATS_FETCH_SUCCESS="STATS_FETCH_SUCCESS";
export const STATS_FETCH_ERROR="STATS_FETCH_ERROR";


export const SET_TRANSACTION_QUERY="SET_TRANSACTION_QUERY";